"use client";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";
import { formatStudyTime, getOptimizedIconUrl } from "@/lib/utils";
import PostFormSection from "../../PostFormSection";
import GroupTimeline from "@/components/GroupTimeline";

export default function GroupDetailPage() {
  const { id } = useParams<{ id: string }>(); const query = useSearchParams(); const supabase = createClient(); const invite = query.get("invite") || "";
  const [userId, setUserId] = useState(""); const [group, setGroup] = useState<any>(null); const [member, setMember] = useState<any>(null); const [ranking, setRanking] = useState<any[]>([]); const [challenges, setChallenges] = useState<any[]>([]); const [challengeResults, setChallengeResults] = useState<Record<string, any[]>>({}); const [members, setMembers] = useState<any[]>([]); const [message, setMessage] = useState(""); const [manageOpen, setManageOpen] = useState(false); const [challengeName, setChallengeName] = useState(""); const [challengeEnd, setChallengeEnd] = useState("");
  const owner = group?.owner_id === userId;
  const load = async (uid?: string) => {
    const current = uid || userId; if (!current) return;
    const [{ data: g }, { data: m }] = await Promise.all([supabase.from("study_groups").select("*").eq("id", id).maybeSingle(), supabase.from("study_group_members").select("*").eq("group_id", id).eq("user_id", current).maybeSingle()]); setGroup(g); setMember(m); if (!m) return;
    const since = new Date(Date.now() - 7 * 86400000).toISOString(); const [{ data: weekRows }, { data: challengeRows }, { data: challengePosts }, memberResponse] = await Promise.all([supabase.from("posts").select("user_id,study_minutes").eq("group_id", id).gte("created_at", since), supabase.from("study_group_challenges").select("*").eq("group_id", id).order("ends_at", { ascending: false }), supabase.from("posts").select("user_id,study_minutes,created_at").eq("group_id", id), fetch(`/api/groups/${id}`)]); setChallenges(challengeRows || []); if (memberResponse.ok) setMembers((await memberResponse.json()).members || []);
    const totals = new Map<string, number>(); (weekRows || []).forEach((row: any) => totals.set(row.user_id, (totals.get(row.user_id) || 0) + (row.study_minutes || 0))); const allIds = [...new Set([...totals.keys(), ...(challengePosts || []).map((row: any) => row.user_id)])]; const { data: profiles } = allIds.length ? await supabase.from("profiles").select("id,display_name,username,icon_url").in("id", allIds) : { data: [] }; const profileMap = new Map((profiles || []).map((p: any) => [p.id, p])); setRanking([...totals.entries()].sort((a, b) => b[1] - a[1]).map(([uid, total], i) => ({ rank: i + 1, total, user: profileMap.get(uid) }))); const results: Record<string, any[]> = {}; (challengeRows || []).forEach((challenge: any) => { const score = new Map<string, number>(); (challengePosts || []).filter((row: any) => row.created_at >= challenge.starts_at && row.created_at <= challenge.ends_at).forEach((row: any) => score.set(row.user_id, (score.get(row.user_id) || 0) + (row.study_minutes || 0))); results[challenge.id] = [...score.entries()].sort((a, b) => b[1] - a[1]).map(([uid, total], i) => ({ rank: i + 1, total, user: profileMap.get(uid) })); }); setChallengeResults(results);
  };
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { const uid = data.user?.id || ""; setUserId(uid); if (uid) load(uid); }); }, [id]);
  const join = async () => { const res = await fetch("/api/groups/join", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ groupId: id, inviteCode: invite }) }); const data = await res.json(); if (!res.ok) return setMessage(data.error || "招待リンクが必要です"); setMessage("グループに参加しました！"); load(); };
  const manage = async (action: string, extra: any = {}) => { if (action === "delete" && !confirm("グループを削除しますか？")) return; const res = await fetch(`/api/groups/${id}`, { method: action === "delete" ? "DELETE" : "PATCH", headers: { "Content-Type": "application/json" }, body: action === "delete" ? undefined : JSON.stringify({ action, ...extra }) }); const data = await res.json(); if (!res.ok) return setMessage(data.error || "操作できませんでした"); if (action === "delete" || action === "leave") return window.location.assign("/groups"); if (action === "regenerate_invite") { setGroup({ ...group, invite_code: data.invite_code }); setMessage("古い招待リンクを無効化しました"); } else load(); };
  const copyInvite = async () => { await navigator.clipboard.writeText(`${window.location.origin}/groups/${id}?invite=${group.invite_code}`); setMessage("招待リンクをコピーしました"); };
  const toggle = async (key: string, value: boolean) => { await supabase.from("study_group_members").update({ [key]: value }).eq("group_id", id).eq("user_id", userId); setMember({ ...member, [key]: value }); };
  const createChallenge = async (e: React.FormEvent) => { e.preventDefault(); const res = await fetch(`/api/groups/${id}/challenges`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: challengeName, startsAt: new Date().toISOString(), endsAt: new Date(`${challengeEnd}T23:59:59`).toISOString() }) }); const data = await res.json(); if (!res.ok) return setMessage(data.error || "勝負を作れませんでした"); setChallengeName(""); setChallengeEnd(""); setMessage("勝負を開始し、メンバーに通知しました！"); load(); };
  const safety = async (action: string, user: string, postId?: string) => { const reason = action === "report" ? prompt("通報理由を入力してください") : ""; if (action === "report" && !reason) return; const res = await fetch("/api/safety", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, userId: user, postId, groupId: id, reason }) }); const data = await res.json(); setMessage(res.ok ? action === "block" ? "ブロックしました" : "通報を受け付けました" : data.error || "操作できませんでした"); if (res.ok && action === "block") load(); };
  if (!userId) return <div className="p-8 text-center">読み込み中...</div>;
  if (!member) return <div className="mx-auto max-w-md p-4"><div className="mt-10 rounded-2xl border border-blue-200 bg-blue-50 p-6 text-center"><p className="text-3xl">🔒</p><h1 className="mt-3 text-lg font-bold">グループに招待されています</h1><p className="mt-2 text-sm text-gray-600">参加すると、仲間だけの投稿とランキングが見られます。</p>{message && <p className="mt-3 text-xs text-red-600">{message}</p>}<button onClick={join} className="mt-5 w-full rounded-full bg-blue-600 py-3 text-sm font-bold text-white">グループに参加する</button><Link href="/groups" className="mt-4 inline-block text-sm text-blue-600">一覧へ戻る</Link></div></div>;
  return <div className="mx-auto max-w-2xl space-y-4 p-4"><Link href="/groups" className="text-sm text-gray-500 no-underline">← グループ一覧</Link><header className="rounded-2xl bg-gradient-to-br from-cyan-600 to-blue-700 p-5 text-white"><div className="flex justify-between gap-3"><div><p className="text-xs">{group?.visibility === "private" ? "🔒 非公開" : "🌍 公開"}</p><h1 className="mt-1 text-xl font-bold">{group?.name}</h1><p className="mt-2 text-xs">{group?.description}</p></div>{owner && <button onClick={copyInvite} className="h-fit rounded-full bg-white/20 px-3 py-2 text-xs font-bold">招待リンク</button>}</div></header>{message && <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}
    <PostFormSection userId={userId} profile={null} groupId={id} />
    <section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="text-sm font-bold text-amber-900">🏆 今週の勉強時間ランキング</h2><div className="mt-3 space-y-2">{ranking.length ? ranking.map((r) => <div key={r.user?.id} className="flex items-center gap-2 rounded-lg bg-white/80 px-3 py-2"><b className="w-5 text-amber-700">{r.rank}</b>{r.user?.icon_url ? <img src={getOptimizedIconUrl(r.user.icon_url, 80)} className="h-7 w-7 rounded-full object-cover" alt="" /> : <i className="fas fa-user-circle text-xl text-gray-300" />}<span className="flex-1 truncate text-sm font-bold">{r.user?.display_name || r.user?.username}</span><b className="text-sm text-amber-700">{formatStudyTime(r.total)}</b></div>) : <p className="py-3 text-center text-xs">まだ記録がありません</p>}</div></section>
    <section className="rounded-xl border border-rose-200 bg-rose-50 p-4"><div className="flex justify-between"><h2 className="text-sm font-bold text-rose-900">🔥 グループ内の勉強勝負</h2>{owner && <button onClick={() => setManageOpen(!manageOpen)} className="text-xs font-bold text-rose-700">管理・作成</button>}</div>{challenges.length ? challenges.map((c) => <div key={c.id} className="mt-3 rounded-lg bg-white/80 p-3"><b className="text-sm">{new Date(c.ends_at) < new Date() ? "🏅 結果" : "⚔️ 開催中"} {c.name}</b><p className="mt-1 text-xs text-gray-600">〜 {new Date(c.ends_at).toLocaleDateString("ja-JP")}</p>{new Date(c.ends_at) < new Date() && challengeResults[c.id]?.[0] && <p className="mt-2 text-xs font-bold text-rose-700">🥇 {challengeResults[c.id][0].user?.display_name || challengeResults[c.id][0].user?.username} が優勝！　{formatStudyTime(challengeResults[c.id][0].total)}</p>}</div>) : <p className="mt-2 text-xs text-rose-800">作成者が期間を決めて勝負を始められます。</p>}</section>
    <section className="rounded-xl border bg-white p-4"><p className="text-sm font-bold">🔔 このグループの通知</p><label className="mt-3 flex justify-between text-sm">新しい投稿<input type="checkbox" checked={!!member.notify_posts} onChange={(e) => toggle("notify_posts", e.target.checked)} /></label><label className="mt-3 flex justify-between text-sm">ランキング変動<input type="checkbox" checked={!!member.notify_rank} onChange={(e) => toggle("notify_rank", e.target.checked)} /></label></section>
    {manageOpen && owner && <section className="rounded-xl border border-purple-200 bg-purple-50 p-4 space-y-3"><div className="flex gap-2"><button onClick={() => manage("regenerate_invite")} className="flex-1 rounded-lg border border-purple-200 bg-white py-2 text-xs font-bold text-purple-700">招待リンクを再発行</button><button onClick={() => manage("delete")} className="rounded-lg bg-red-500 px-3 text-xs font-bold text-white">削除</button></div><form onSubmit={createChallenge} className="space-y-2 border-t border-purple-200 pt-3"><p className="text-xs font-bold text-purple-900">新しい勉強勝負</p><input required value={challengeName} onChange={(e) => setChallengeName(e.target.value)} placeholder="例：夏休み30時間勝負" className="w-full rounded-lg border-gray-300 text-sm" /><input required type="date" value={challengeEnd} onChange={(e) => setChallengeEnd(e.target.value)} className="w-full rounded-lg border-gray-300 text-sm" /><button className="w-full rounded-lg bg-purple-600 py-2 text-xs font-bold text-white">勝負を開始する</button></form><div className="border-t border-purple-200 pt-3"><p className="text-xs font-bold text-purple-900">メンバー管理</p>{members.filter((m) => m.user_id !== userId).map((m) => <div key={m.user_id} className="mt-2 flex text-sm"><span className="flex-1">{m.profile?.display_name || m.profile?.username || "メンバー"}</span><button onClick={() => manage("remove_member", { userId: m.user_id })} className="text-xs text-red-600">外す</button></div>)}</div></section>}
    {!owner && <button onClick={() => manage("leave")} className="w-full rounded-xl border border-red-200 bg-white py-3 text-sm font-bold text-red-600">グループを退出する</button>}
    <section className="space-y-2"><h2 className="text-sm font-bold">グループの投稿</h2><GroupTimeline groupId={id} userId={userId} /></section>
  </div>;
}
