create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  type text not null default 'feedback',
  created_at timestamptz not null default now()
);

alter table public.user_feedback enable row level security;

create policy "Users can insert their own feedback"
  on public.user_feedback for insert
  with check (auth.uid() = user_id);

create policy "Only admin can view feedback"
  on public.user_feedback for select
  using (auth.uid() in (select id from auth.users where raw_user_meta_data->>'role' = 'admin'));
